### ISSUE TITLE
deprecation in symfony 6.x and 7.x

### ISSUE THREAD

**Issue by thenerka1** [Tomsgu/PDFMergerBundle#7]
User Deprecated: Method "Symfony\Component\HttpKernel\Bundle\Bundle::build()" might add "void" as a native return type declaration in the future. Do the same in child class "Tomsgu\PdfMergerBundle\TomsguPdfMergerBundle" now to avoid errors or add an explicit @return annotation to suppress this message.

add `: void` in tomsgu/pdf-merger-bundle/src/TomsguPdfMergerBundle `build` function

**Comment by Tomsgu** [comment]
Fixed in https://github.com/Tomsgu/PDFMergerBundle/pull/8
